### ISSUE TITLE
Mock API [Improvement]

### ISSUE THREAD

**Issue by ahkeno** [api-collab/apicollab-ui#2]
would be great , if you add the mock API 
https://medium.freecodecamp.org/rapid-development-via-mock-apis-e559087be066

**Comment by kand617** [comment]
Interesting,  @ahkeno perhaps you can implement and do a PR? 
You can find the API specification here:
https://github.com/api-collab/api-collab-server/blob/master/src/main/resources/swagger.yml

**Comment by kand617** [comment]
The API has been updated, the new changes should make it easier to utilise json-server.
Will be making a PR soon

**Comment by kand617** [comment]
@ahkeno please see PR #11

**Comment by ahkeno** [comment]
reviewed [https://github.com/api-collab/apicollab-ui/pull/11](PR)
